### ISSUE TITLE
大佬教程能否写的详细点呢

### ISSUE THREAD

**Issue by gakiyukr** [himcs/LeishenAuto#1]
如题，这教程一般人真心看不懂，都没提到需要那些权限，如何设置。

**Comment by Noda2333** [comment]
> 如题，这教程一般人真心看不懂，都没提到需要那些权限，如何设置。

就和一般的actions配置类似，在仓库secret里添加LEISHEN_USERNAME和LEISHEN_PASSWORD两项，再打开actions里的workflow就行了，密码是加密过后的，可以去雷神官网抓包看登录请求的密码

**Comment by himcs** [comment]
更新了一下文档,就一个简单的定时任务
